package model;
// Generated 27/11/2014 02:27:56 AM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

/**
 * Caracteristicas generated by hbm2java
 */
public class Caracteristicas implements java.io.Serializable {

	private CaracteristicasId id;
	private Nivelconfig nivelconfig;
	private Integer tamanio;
	private Integer tipoDato;
	private String cifrado;
	private String transformado;
	private String caracter;
	private Integer posicion;
	private String campo;
	private String descripcion;
	private Integer orden;
	private Set queries = new HashSet(0);

	public Caracteristicas() {
	}

	public Caracteristicas(CaracteristicasId id, Nivelconfig nivelconfig) {
		this.id = id;
		this.nivelconfig = nivelconfig;
	}

	public Caracteristicas(CaracteristicasId id, Nivelconfig nivelconfig,
			Integer tamanio, Integer tipoDato, String cifrado,
			String transformado, String caracter, Integer posicion,
			String campo, String descripcion, Integer orden, Set queries) {
		this.id = id;
		this.nivelconfig = nivelconfig;
		this.tamanio = tamanio;
		this.tipoDato = tipoDato;
		this.cifrado = cifrado;
		this.transformado = transformado;
		this.caracter = caracter;
		this.posicion = posicion;
		this.campo = campo;
		this.descripcion = descripcion;
		this.orden = orden;
		this.queries = queries;
	}

	public CaracteristicasId getId() {
		return this.id;
	}

	public void setId(CaracteristicasId id) {
		this.id = id;
	}

	public Nivelconfig getNivelconfig() {
		return this.nivelconfig;
	}

	public void setNivelconfig(Nivelconfig nivelconfig) {
		this.nivelconfig = nivelconfig;
	}

	public Integer getTamanio() {
		return this.tamanio;
	}

	public void setTamanio(Integer tamanio) {
		this.tamanio = tamanio;
	}

	public Integer getTipoDato() {
		return this.tipoDato;
	}

	public void setTipoDato(Integer tipoDato) {
		this.tipoDato = tipoDato;
	}

	public String getCifrado() {
		return this.cifrado;
	}

	public void setCifrado(String cifrado) {
		this.cifrado = cifrado;
	}

	public String getTransformado() {
		return this.transformado;
	}

	public void setTransformado(String transformado) {
		this.transformado = transformado;
	}

	public String getCaracter() {
		return this.caracter;
	}

	public void setCaracter(String caracter) {
		this.caracter = caracter;
	}

	public Integer getPosicion() {
		return this.posicion;
	}

	public void setPosicion(Integer posicion) {
		this.posicion = posicion;
	}

	public String getCampo() {
		return this.campo;
	}

	public void setCampo(String campo) {
		this.campo = campo;
	}

	public String getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

	public Integer getOrden() {
		return this.orden;
	}

	public void setOrden(Integer orden) {
		this.orden = orden;
	}

	public Set getQueries() {
		return this.queries;
	}

	public void setQueries(Set queries) {
		this.queries = queries;
	}

}
