package model;
// Generated 27/11/2014 02:27:56 AM by Hibernate Tools 3.4.0.CR1

/**
 * CaracteristicasId generated by hbm2java
 */
public class CaracteristicasId implements java.io.Serializable {

	private int idCaracteristicas;
	private int idNivelConfig;
	private int idEtiqueta;
	private int idPlantilla;

	public CaracteristicasId() {
	}

	public CaracteristicasId(int idCaracteristicas, int idNivelConfig,
			int idEtiqueta, int idPlantilla) {
		this.idCaracteristicas = idCaracteristicas;
		this.idNivelConfig = idNivelConfig;
		this.idEtiqueta = idEtiqueta;
		this.idPlantilla = idPlantilla;
	}

	public int getIdCaracteristicas() {
		return this.idCaracteristicas;
	}

	public void setIdCaracteristicas(int idCaracteristicas) {
		this.idCaracteristicas = idCaracteristicas;
	}

	public int getIdNivelConfig() {
		return this.idNivelConfig;
	}

	public void setIdNivelConfig(int idNivelConfig) {
		this.idNivelConfig = idNivelConfig;
	}

	public int getIdEtiqueta() {
		return this.idEtiqueta;
	}

	public void setIdEtiqueta(int idEtiqueta) {
		this.idEtiqueta = idEtiqueta;
	}

	public int getIdPlantilla() {
		return this.idPlantilla;
	}

	public void setIdPlantilla(int idPlantilla) {
		this.idPlantilla = idPlantilla;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof CaracteristicasId))
			return false;
		CaracteristicasId castOther = (CaracteristicasId) other;

		return (this.getIdCaracteristicas() == castOther.getIdCaracteristicas())
				&& (this.getIdNivelConfig() == castOther.getIdNivelConfig())
				&& (this.getIdEtiqueta() == castOther.getIdEtiqueta())
				&& (this.getIdPlantilla() == castOther.getIdPlantilla());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getIdCaracteristicas();
		result = 37 * result + this.getIdNivelConfig();
		result = 37 * result + this.getIdEtiqueta();
		result = 37 * result + this.getIdPlantilla();
		return result;
	}

}
