package model;


// Generated 27/11/2014 02:27:56 AM by Hibernate Tools 3.4.0.CR1

/**
 * CaracteristicasId generated by hbm2java
 */
public class CaracteristicasId implements java.io.Serializable {

	private Integer idCaracteristicas;
	private Integer idNivelConfig;
	private Integer idEtiqueta;
	private Integer idPlantilla;

	public CaracteristicasId() {
	}

	public CaracteristicasId(Integer idCaracteristicas, Integer idNivelConfig,
			Integer idEtiqueta, Integer idPlantilla) {
		this.idCaracteristicas = idCaracteristicas;
		this.idNivelConfig = idNivelConfig;
		this.idEtiqueta = idEtiqueta;
		this.idPlantilla = idPlantilla;
	}

	public Integer getIdCaracteristicas() {
		return this.idCaracteristicas;
	}

	public void setIdCaracteristicas(Integer idCaracteristicas) {
		this.idCaracteristicas = idCaracteristicas;
	}

	public Integer getIdNivelConfig() {
		return this.idNivelConfig;
	}

	public void setIdNivelConfig(Integer idNivelConfig) {
		this.idNivelConfig = idNivelConfig;
	}

	public Integer getIdEtiqueta() {
		return this.idEtiqueta;
	}

	public void setIdEtiqueta(Integer idEtiqueta) {
		this.idEtiqueta = idEtiqueta;
	}

	public Integer getIdPlantilla() {
		return this.idPlantilla;
	}

	public void setIdPlantilla(Integer idPlantilla) {
		this.idPlantilla = idPlantilla;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof CaracteristicasId))
			return false;
		CaracteristicasId castOther = (CaracteristicasId) other;

		return (this.getIdCaracteristicas() == castOther.getIdCaracteristicas())
				&& (this.getIdNivelConfig() == castOther.getIdNivelConfig())
				&& (this.getIdEtiqueta() == castOther.getIdEtiqueta())
				&& (this.getIdPlantilla() == castOther.getIdPlantilla());
	}
}
