package model;
// Generated 27/11/2014 02:27:56 AM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

/**
 * Etiqueta generated by hbm2java
 */
public class Etiqueta implements java.io.Serializable {

	private EtiquetaId id;
	private Plantilla plantilla;
	private String tipoEtiqueta;
	private Integer cantidad;
	private Set nivelconfigs = new HashSet(0);

	public Etiqueta() {
	}

	public Etiqueta(EtiquetaId id, Plantilla plantilla) {
		this.id = id;
		this.plantilla = plantilla;
	}

	public Etiqueta(EtiquetaId id, Plantilla plantilla, String tipoEtiqueta,
			Integer cantidad, Set nivelconfigs) {
		this.id = id;
		this.plantilla = plantilla;
		this.tipoEtiqueta = tipoEtiqueta;
		this.cantidad = cantidad;
		this.nivelconfigs = nivelconfigs;
	}

	public EtiquetaId getId() {
		return this.id;
	}

	public void setId(EtiquetaId id) {
		this.id = id;
	}

	public Plantilla getPlantilla() {
		return this.plantilla;
	}

	public void setPlantilla(Plantilla plantilla) {
		this.plantilla = plantilla;
	}

	public String getTipoEtiqueta() {
		return this.tipoEtiqueta;
	}

	public void setTipoEtiqueta(String tipoEtiqueta) {
		this.tipoEtiqueta = tipoEtiqueta;
	}

	public Integer getCantidad() {
		return this.cantidad;
	}

	public void setCantidad(Integer cantidad) {
		this.cantidad = cantidad;
	}

	public Set getNivelconfigs() {
		return this.nivelconfigs;
	}

	public void setNivelconfigs(Set nivelconfigs) {
		this.nivelconfigs = nivelconfigs;
	}

}
