package model;
// Generated 27/11/2014 02:27:56 AM by Hibernate Tools 3.4.0.CR1

/**
 * EtiquetaId generated by hbm2java
 */
public class EtiquetaId implements java.io.Serializable {

	private int idEtiqueta;
	private int idPlantilla;

	public EtiquetaId() {
	}

	public EtiquetaId(int idEtiqueta, int idPlantilla) {
		this.idEtiqueta = idEtiqueta;
		this.idPlantilla = idPlantilla;
	}

	public int getIdEtiqueta() {
		return this.idEtiqueta;
	}

	public void setIdEtiqueta(int idEtiqueta) {
		this.idEtiqueta = idEtiqueta;
	}

	public int getIdPlantilla() {
		return this.idPlantilla;
	}

	public void setIdPlantilla(int idPlantilla) {
		this.idPlantilla = idPlantilla;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof EtiquetaId))
			return false;
		EtiquetaId castOther = (EtiquetaId) other;

		return (this.getIdEtiqueta() == castOther.getIdEtiqueta())
				&& (this.getIdPlantilla() == castOther.getIdPlantilla());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getIdEtiqueta();
		result = 37 * result + this.getIdPlantilla();
		return result;
	}

}
