package model;
// Generated 27/11/2014 02:27:56 AM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

/**
 * Nivelconfig generated by hbm2java
 */
public class Nivelconfig implements java.io.Serializable {

	private NivelconfigId id;
	private Etiqueta etiqueta;
	private Integer posicion;
	private Set caracteristicases = new HashSet(0);

	public Nivelconfig() {
	}

	public Nivelconfig(NivelconfigId id, Etiqueta etiqueta) {
		this.id = id;
		this.etiqueta = etiqueta;
	}

	public Nivelconfig(NivelconfigId id, Etiqueta etiqueta, Integer posicion,
			Set caracteristicases) {
		this.id = id;
		this.etiqueta = etiqueta;
		this.posicion = posicion;
		this.caracteristicases = caracteristicases;
	}

	public NivelconfigId getId() {
		return this.id;
	}

	public void setId(NivelconfigId id) {
		this.id = id;
	}

	public Etiqueta getEtiqueta() {
		return this.etiqueta;
	}

	public void setEtiqueta(Etiqueta etiqueta) {
		this.etiqueta = etiqueta;
	}

	public Integer getPosicion() {
		return this.posicion;
	}

	public void setPosicion(Integer posicion) {
		this.posicion = posicion;
	}

	public Set getCaracteristicases() {
		return this.caracteristicases;
	}

	public void setCaracteristicases(Set caracteristicases) {
		this.caracteristicases = caracteristicases;
	}

}
