package model;
// Generated 27/11/2014 02:27:56 AM by Hibernate Tools 3.4.0.CR1

/**
 * NivelconfigId generated by hbm2java
 */
public class NivelconfigId implements java.io.Serializable {

	private int idNivelConfig;
	private int idEtiqueta;
	private int idPlantilla;

	public NivelconfigId() {
	}

	public NivelconfigId(int idNivelConfig, int idEtiqueta, int idPlantilla) {
		this.idNivelConfig = idNivelConfig;
		this.idEtiqueta = idEtiqueta;
		this.idPlantilla = idPlantilla;
	}

	public int getIdNivelConfig() {
		return this.idNivelConfig;
	}

	public void setIdNivelConfig(int idNivelConfig) {
		this.idNivelConfig = idNivelConfig;
	}

	public int getIdEtiqueta() {
		return this.idEtiqueta;
	}

	public void setIdEtiqueta(int idEtiqueta) {
		this.idEtiqueta = idEtiqueta;
	}

	public int getIdPlantilla() {
		return this.idPlantilla;
	}

	public void setIdPlantilla(int idPlantilla) {
		this.idPlantilla = idPlantilla;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof NivelconfigId))
			return false;
		NivelconfigId castOther = (NivelconfigId) other;

		return (this.getIdNivelConfig() == castOther.getIdNivelConfig())
				&& (this.getIdEtiqueta() == castOther.getIdEtiqueta())
				&& (this.getIdPlantilla() == castOther.getIdPlantilla());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getIdNivelConfig();
		result = 37 * result + this.getIdEtiqueta();
		result = 37 * result + this.getIdPlantilla();
		return result;
	}

}
