package model;
// Generated 27/11/2014 02:27:56 AM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

/**
 * Opciones generated by hbm2java
 */
public class Opciones implements java.io.Serializable {

	private int idOpciones;
	private String descripcion;
	private Set perfils = new HashSet(0);

	public Opciones() {
	}

	public Opciones(int idOpciones) {
		this.idOpciones = idOpciones;
	}

	public Opciones(int idOpciones, String descripcion, Set perfils) {
		this.idOpciones = idOpciones;
		this.descripcion = descripcion;
		this.perfils = perfils;
	}

	public int getIdOpciones() {
		return this.idOpciones;
	}

	public void setIdOpciones(int idOpciones) {
		this.idOpciones = idOpciones;
	}

	public String getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

	public Set getPerfils() {
		return this.perfils;
	}

	public void setPerfils(Set perfils) {
		this.perfils = perfils;
	}

}
