package model;
import java.util.HashSet;
import java.util.Set;

/**
 * Perfil generated by hbm2java
 */
public class Perfil implements java.io.Serializable {

	private int idPerfil;
	private String nombreperfil;
	private Set opcioneses = new HashSet(0);
	private Set usuarios = new HashSet(0);

	public Perfil() {
	}

	public Perfil(int idPerfil) {
		this.idPerfil = idPerfil;
	}

	public Perfil(int idPerfil, String nombreperfil, Set opcioneses,
			Set usuarios) {
		this.idPerfil = idPerfil;
		this.nombreperfil = nombreperfil;
		this.opcioneses = opcioneses;
		this.usuarios = usuarios;
	}

	public int getIdPerfil() {
		return this.idPerfil;
	}

	public void setIdPerfil(int idPerfil) {
		this.idPerfil = idPerfil;
	}

	public String getNombreperfil() {
		return this.nombreperfil;
	}

	public void setNombreperfil(String nombreperfil) {
		this.nombreperfil = nombreperfil;
	}

	public Set getOpcioneses() {
		return this.opcioneses;
	}

	public void setOpcioneses(Set opcioneses) {
		this.opcioneses = opcioneses;
	}

	public Set getUsuarios() {
		return this.usuarios;
	}

	public void setUsuarios(Set usuarios) {
		this.usuarios = usuarios;
	}

}
