package model;
// Generated 27/11/2014 02:27:56 AM by Hibernate Tools 3.4.0.CR1

/**
 * Query generated by hbm2java
 */
public class Query implements java.io.Serializable {

	private QueryId id;
	private Caracteristicas caracteristicas;
	private String textoQuery;
	private String descripcion;
	private String nombre;

	public Query() {
	}

	public Query(QueryId id, Caracteristicas caracteristicas) {
		this.id = id;
		this.caracteristicas = caracteristicas;
	}

	public Query(QueryId id, Caracteristicas caracteristicas,
			String textoQuery, String descripcion, String nombre) {
		this.id = id;
		this.caracteristicas = caracteristicas;
		this.textoQuery = textoQuery;
		this.descripcion = descripcion;
		this.nombre = nombre;
	}

	public QueryId getId() {
		return this.id;
	}

	public void setId(QueryId id) {
		this.id = id;
	}

	public Caracteristicas getCaracteristicas() {
		return this.caracteristicas;
	}

	public void setCaracteristicas(Caracteristicas caracteristicas) {
		this.caracteristicas = caracteristicas;
	}

	public String getTextoQuery() {
		return this.textoQuery;
	}

	public void setTextoQuery(String textoQuery) {
		this.textoQuery = textoQuery;
	}

	public String getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

}
