package model;
// Generated 27/11/2014 02:27:56 AM by Hibernate Tools 3.4.0.CR1

/**
 * Usuario generated by hbm2java
 */
public class Usuario implements java.io.Serializable {

	private UsuarioId id;
	private Perfil perfil;
	private String nombre;
	private String apellidoPaterno;
	private String apellidoMaterno;
	private String usuario;
	private String contrasenia;
	private String sexo;
	private Integer edad;
	private Integer estado;

	public Usuario() {
	}

	public Usuario(UsuarioId id, Perfil perfil) {
		this.id = id;
		this.perfil = perfil;
	}

	public Usuario(UsuarioId id, Perfil perfil, String nombre,
			String apellidoPaterno, String apellidoMaterno, String usuario,
			String contrasenia, String sexo, Integer edad, Integer estado) {
		this.id = id;
		this.perfil = perfil;
		this.nombre = nombre;
		this.apellidoPaterno = apellidoPaterno;
		this.apellidoMaterno = apellidoMaterno;
		this.usuario = usuario;
		this.contrasenia = contrasenia;
		this.sexo = sexo;
		this.edad = edad;
		this.estado = estado;
	}

	public UsuarioId getId() {
		return this.id;
	}

	public void setId(UsuarioId id) {
		this.id = id;
	}

	public Perfil getPerfil() {
		return this.perfil;
	}

	public void setPerfil(Perfil perfil) {
		this.perfil = perfil;
	}

	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	public String getApellidoPaterno() {
		return this.apellidoPaterno;
	}

	public void setApellidoPaterno(String apellidoPaterno) {
		this.apellidoPaterno = apellidoPaterno;
	}

	public String getApellidoMaterno() {
		return this.apellidoMaterno;
	}

	public void setApellidoMaterno(String apellidoMaterno) {
		this.apellidoMaterno = apellidoMaterno;
	}

	public String getUsuario() {
		return this.usuario;
	}

	public void setUsuario(String usuario) {
		this.usuario = usuario;
	}

	public String getContrasenia() {
		return this.contrasenia;
	}

	public void setContrasenia(String contrasenia) {
		this.contrasenia = contrasenia;
	}

	public String getSexo() {
		return this.sexo;
	}

	public void setSexo(String sexo) {
		this.sexo = sexo;
	}

	public Integer getEdad() {
		return this.edad;
	}

	public void setEdad(Integer edad) {
		this.edad = edad;
	}

	public Integer getEstado() {
		return this.estado;
	}

	public void setEstado(Integer estado) {
		this.estado = estado;
	}

}
