package model;
// Generated 27/11/2014 02:27:56 AM by Hibernate Tools 3.4.0.CR1

/**
 * UsuarioId generated by hbm2java
 */
public class UsuarioId implements java.io.Serializable {

	private int idUsuario;
	private int idPerfil;

	public UsuarioId() {
	}

	public UsuarioId(int idUsuario, int idPerfil) {
		this.idUsuario = idUsuario;
		this.idPerfil = idPerfil;
	}

	public int getIdUsuario() {
		return this.idUsuario;
	}

	public void setIdUsuario(int idUsuario) {
		this.idUsuario = idUsuario;
	}

	public int getIdPerfil() {
		return this.idPerfil;
	}

	public void setIdPerfil(int idPerfil) {
		this.idPerfil = idPerfil;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof UsuarioId))
			return false;
		UsuarioId castOther = (UsuarioId) other;

		return (this.getIdUsuario() == castOther.getIdUsuario())
				&& (this.getIdPerfil() == castOther.getIdPerfil());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getIdUsuario();
		result = 37 * result + this.getIdPerfil();
		return result;
	}

}
