-- MySQL Script generated by MySQL Workbench
-- 11/27/14 02:21:50
-- Model: New Model    Version: 1.0
SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema dbsigae
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `dbsigae` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `dbsigae` ;

-- -----------------------------------------------------
-- Table `dbsigae`.`Perfil`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbsigae`.`Perfil` (
  `idPerfil` INT NOT NULL,
  `nombreperfil` VARCHAR(20) NULL,
  PRIMARY KEY (`idPerfil`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dbsigae`.`Usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbsigae`.`Usuario` (
  `idUsuario` INT NOT NULL,
  `idPerfil` INT NOT NULL,
  `nombre` VARCHAR(20) NULL,
  `apellido_paterno` VARCHAR(10) NULL,
  `apellido_materno` VARCHAR(10) NULL,
  `usuario` VARCHAR(6) NULL,
  `contrasenia` VARCHAR(8) NULL,
  `sexo` VARCHAR(1) NULL,
  `edad` INT NULL,
  `estado` INT(1) NULL,
  PRIMARY KEY (`idUsuario`, `idPerfil`),
  INDEX `fk_Usuario_Perfil_idx` (`idPerfil` ASC),
  CONSTRAINT `fk_Usuario_Perfil`
    FOREIGN KEY (`idPerfil`)
    REFERENCES `dbsigae`.`Perfil` (`idPerfil`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dbsigae`.`Opciones`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbsigae`.`Opciones` (
  `idOpciones` INT NOT NULL,
  `Descripcion` VARCHAR(20) NULL,
  PRIMARY KEY (`idOpciones`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dbsigae`.`PLANTILLA`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbsigae`.`PLANTILLA` (
  `idPLANTILLA` INT NOT NULL,
  `nombre` VARCHAR(25) NULL,
  `Direccion` VARCHAR(30) NULL,
  `query` VARCHAR(100) NULL,
  PRIMARY KEY (`idPLANTILLA`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dbsigae`.`ETIQUETA`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbsigae`.`ETIQUETA` (
  `idETIQUETA` INT NOT NULL,
  `idPLANTILLA` INT NOT NULL,
  `Tipo_Etiqueta` VARCHAR(20) NULL,
  `cantidad` INT NULL,
  PRIMARY KEY (`idETIQUETA`, `idPLANTILLA`),
  INDEX `fk_ETIQUETA_PLANTILLA1_idx` (`idPLANTILLA` ASC),
  CONSTRAINT `fk_ETIQUETA_PLANTILLA1`
    FOREIGN KEY (`idPLANTILLA`)
    REFERENCES `dbsigae`.`PLANTILLA` (`idPLANTILLA`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dbsigae`.`NivelConfig`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbsigae`.`NivelConfig` (
  `idNivelConfig` INT NOT NULL,
  `Posicion` INT NULL,
  `idETIQUETA` INT NOT NULL,
  `idPLANTILLA` INT NOT NULL,
  PRIMARY KEY (`idNivelConfig`, `idETIQUETA`, `idPLANTILLA`),
  INDEX `fk_NivelConfig_ETIQUETA1_idx` (`idETIQUETA` ASC, `idPLANTILLA` ASC),
  CONSTRAINT `fk_NivelConfig_ETIQUETA1`
    FOREIGN KEY (`idETIQUETA` , `idPLANTILLA`)
    REFERENCES `dbsigae`.`ETIQUETA` (`idETIQUETA` , `idPLANTILLA`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dbsigae`.`CARACTERISTICAS`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbsigae`.`CARACTERISTICAS` (
  `idCARACTERISTICAS` INT NOT NULL,
  `Tamanio` INT NULL,
  `Tipo_Dato` VARCHAR(15) NULL,
  `Cifrado` VARCHAR(1) NULL,
  `Transformado` VARCHAR(2) NULL,
  `caracter` VARCHAR(1) NULL,
  `posicion` VARCHAR(10) NULL,
  `idNivelConfig` INT NOT NULL,
  `idETIQUETA` INT NOT NULL,
  `idPLANTILLA` INT NOT NULL,
  `Campo` VARCHAR(25) NULL,
  `Descripcion` VARCHAR(15) NULL,
  `Orden` VARCHAR(1) NULL,
  PRIMARY KEY (`idCARACTERISTICAS`, `idNivelConfig`, `idETIQUETA`, `idPLANTILLA`),
  INDEX `fk_CARACTERISTICAS_NivelConfig1_idx` (`idNivelConfig` ASC, `idETIQUETA` ASC, `idPLANTILLA` ASC),
  CONSTRAINT `fk_CARACTERISTICAS_NivelConfig1`
    FOREIGN KEY (`idNivelConfig` , `idETIQUETA` , `idPLANTILLA`)
    REFERENCES `dbsigae`.`NivelConfig` (`idNivelConfig` , `idETIQUETA` , `idPLANTILLA`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dbsigae`.`Query`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbsigae`.`Query` (
  `idQuery` INT NOT NULL,
  `texto_query` VARCHAR(100) NULL,
  `Descripcion` VARCHAR(35) NULL,
  `idCARACTERISTICAS` INT NOT NULL,
  `idNivelConfig` INT NOT NULL,
  `idETIQUETA` INT NOT NULL,
  `idPLANTILLA` INT NOT NULL,
  `Nombre` VARCHAR(15) NULL,
  PRIMARY KEY (`idQuery`, `idCARACTERISTICAS`, `idNivelConfig`, `idETIQUETA`, `idPLANTILLA`),
  INDEX `fk_Query_CARACTERISTICAS1_idx` (`idCARACTERISTICAS` ASC, `idNivelConfig` ASC, `idETIQUETA` ASC, `idPLANTILLA` ASC),
  CONSTRAINT `fk_Query_CARACTERISTICAS1`
    FOREIGN KEY (`idCARACTERISTICAS` , `idNivelConfig` , `idETIQUETA` , `idPLANTILLA`)
    REFERENCES `dbsigae`.`CARACTERISTICAS` (`idCARACTERISTICAS` , `idNivelConfig` , `idETIQUETA` , `idPLANTILLA`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dbsigae`.`PerfilOpciones`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbsigae`.`PerfilOpciones` (
  `idPerfil` INT NOT NULL,
  `idOpciones` INT NOT NULL,
  PRIMARY KEY (`idPerfil`, `idOpciones`),
  INDEX `fk_Perfil_has_Opciones_Opciones2_idx` (`idOpciones` ASC),
  INDEX `fk_Perfil_has_Opciones_Perfil2_idx` (`idPerfil` ASC),
  CONSTRAINT `fk_Perfil_has_Opciones_Perfil2`
    FOREIGN KEY (`idPerfil`)
    REFERENCES `dbsigae`.`Perfil` (`idPerfil`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Perfil_has_Opciones_Opciones2`
    FOREIGN KEY (`idOpciones`)
    REFERENCES `dbsigae`.`Opciones` (`idOpciones`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
